### ISSUE TITLE
BUG - accept `null` values in JSON

### ISSUE THREAD

**Issue by oreoana** [fivetran/dbt_shopify#20] opened 2021-07-01 18:25 UTC
**Are you a current Fivetran customer?** 
Yes -- Blue Bottle Coffee

**Describe the bug**
A database error occurs when there are `null` values in the JSON. Example JSON in the `receipt` column of `stg_shopify__transaction` below:

```json
{
  "charges": {
    "data": [
      {
        "balance_transaction": {
          "exchange_rate": null
        }
      }
    ]
  }
}
```

**Steps to reproduce**
When running the `shopify__transactions` model, I see this error:
```
Database Error in model shopify__transactions (models/shopify__transactions.sql)
  Invalid input syntax for type numeric
  DETAIL:  
    -----------------------------------------------
    error:  Invalid input syntax for type numeric
    code:      8001
    context:   value: ""
    query:     1559843
    location:  cg_util.cpp:621
    process:   query6_100_1559843 [pid=29142]
    -----------------------------------------------
```

**Package Version**

```yml
  - package: fivetran/shopify
    version: 0.4.1
    # documentation: https://github.com/fivetran/dbt_shopify
```

**Warehouse**

 
- [ ] BigQuery
- [x] Redshift
- [ ] Snowflake
- [ ] Postgres
- [ ] Databricks
- [ ] Other (provide details below)

**Comment by fivetran-joemarkiewicz** [comment] 2021-07-01 20:36
Hi @oreoana Thanks so much for opening this ticket! After our call this afternoon I have a good idea of what we need to do to rectify this issue. I will start working on a branch to fix this bug and will let you know here once a fix is applied.

**Comment by fivetran-joemarkiewicz** [comment] 2021-07-02 15:27
@oreoana I believe I found the solution to the bug mentioned. Essentially the cause is what we suspected. The previous logic was able to coalesce the field to null if the `exchange_rate` object did not exist. However redshift seems to see `exchange_reate: null` as both a null and not-null value. 

Therefore, my solution was to leverage the `nullif` record at the json_extract macro to capture the null before it can be compiled within the query. I tested this on my Redshift and other databases and it worked with the intended results. Feel free to give the working branch another go on your side and let me know if it works or you experience any issues. You can use the below config in your `packages.yml`:
```yml
packages:
  - git: https://github.com/fivetran/dbt_shopify.git
    revision: bug/null-exchange-rate
    warn-unpinned: false
```

Let me know, thanks! 😄

**Comment by oreoana** [comment] 2021-07-02 16:33
@fivetran-joemarkiewicz just tried and it worked! Thank you 🙏

**Comment by fivetran-joemarkiewicz** [comment] 2021-07-02 19:14
That's great to hear! I just merged and cut a new release for the shopify package `v0.4.2`. This should be live on the dbt hub later today. 

Thank you again for opening this issue and please let me know if you have any further questions when using the package.

**Closed by fivetran-joemarkiewicz** 2021-07-02 19:14 UTC
Labels: bug
